### ISSUE TITLE
Exporting graph as image hangs

### ISSUE THREAD

**Issue by Aveheuzed** [QuinnFreedman/nimgraphviz#4]
Hey,
I encountered a problem saving my graphs as images, even using the sample code built in the library.
The proc in question is `exportImage`; it just hangs up and never returns.
I'm running on Ubuntu 20.04.3 LTS x86_64 // Nim Compiler Version 1.0.6 [Linux: amd64] // dot - graphviz version 2.43.0 (0).
The problem happens both on relase and debug builds.
I instrumented the faulty proc, like this (lines 329-347) :
```nim
    let process = startProcess(command, args=args, options={poUsePath})
    let stdin = process.inputStream
    stdin.write(text)
    echo "process started, dot code written to stdin"
    var stdout = outputStream(process)
    var result = TaintedString""
    var line = newStringOfCap(120).TaintedString
    echo "before the `while` loop"
    while true:
      echo "in the `while` loop"
      if stdout.readLine(line):
        echo "in the `if` block"
        result.string.add(line.string)
        result.string.add("\n")
      elif not running(process):
              echo "in the `elif` block"
              break
    echo "after the `while` loop"
    close(process)
```
Building command : `nim c -r src/nimgraphviz.nim`
Output :

> Exporting graph as PNG...
> process started, dot code written to stdin
> before the `while` loop
> in the `while` loop
> ^CTraceback (most recent call last)
> /home/aveheuzed/Documents/nimgraphviz/src/nimgraphviz.nim(379) nimgraphviz
> /home/aveheuzed/Documents/nimgraphviz/src/nimgraphviz.nim(339) exportImage
> /usr/lib/nim/pure/streams.nim(884) readLine
> /usr/lib/nim/pure/streams.nim(1142) fsReadLine
> /usr/lib/nim/system/io.nim(313) readLine
> SIGINT: Interrupted by Ctrl-C.
> Error: execution of an external program failed: '/home/aveheuzed/Documents/nimgraphviz/src/nimgraphviz '

A solution I found is the following :
```nim
    let process = startProcess(command, args=args, options={poUsePath})
    let stdin = process.inputStream
    stdin.write(text)
    stdin.close()
    var stdout = outputStream(process)
    discard process.waitForExit()
    let result = stdout.readAll()
    close(process)
```
The caveat being that it requires closing stdin manually, even though the docs guard against it.
Nonetheless, it seems to indicate that the EOT maneuver doesn't work, and that `dot` still expects more input.
An other solution that could be considered is using a (temporary) file to write the dot script to.

Whitchever solution you favor, I'm willing to do the coding; I just wanted approval before commiting.

**Comment by QuinnFreedman** [comment]
That solution looks good to me. If it works I think it's fine. I'll happily accept the PR if you want to write it.
